#!/bin/bash
#
# rails_server
#
# chkconfig: - 99 15
# description: Start the rails web server 
#

# Source function library.
. /etc/rc.d/init.d/functions

prog="Rails_Server"

start() {
        echo -n $"Starting $prog: "
        while !(mysql -u root --password='new-password' -e "show databases" -h 10.0.0.2 mysql); do
                echo DB still not up, retrying....
                sleep 5
        done

        while [ ! -d /vagrant/AGM-P161 ]; do
                echo /vagrant directory still not mounted. Retrying...
                sleep 5
        done
        cd  /vagrant/AGM-P161
        sudo su - vagrant -c "/vagrant/AGM-P161/bin/rails server -e production -d"
        RETVAL=$?
        return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	kill -9  `cat /vagrant/AGM-P161/tmp/pids/server.pid`
	RETVAL=$?
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: $prog {start|stop|restart}"
	RETVAL=2
esac

exit $RETVAL
